### ISSUE TITLE
Ignoring SSL Certificates On Validation

### ISSUE THREAD

**Issue by jacojvv-dev** [openiddict/openiddict-core#1756]
### Confirm you've already contributed to this project or that you sponsor it

- [X] I confirm I'm a sponsor or a contributor

### Version

4.x

### Question

Hi all.

I am facing some issues related to self signed certificates and docker. I was able to get the identity service up and running with SSL enabled easily, the problem - however, is that I cannot for the life of me get a secondary service to trust the certificate being used for SSL on the identity service.

I have tried several approaches at this point. More than I care to mention, and none have worked for me.

As a last resort I tried disabling certificate verification when performing network request but I also have not been able to get this to work.

My validation setup is  standard:

```csharp
builder.Services
    .AddOpenIddict()
    .AddValidation(options =>
    {
        options.SetIssuer(builder.Configuration["IdentityConfiguration:Issuer"]);
        options.UseSystemNetHttp();
        options.UseAspNetCore();
        options.AddEncryptionCertificate(encryptionCertificate);
    });
```

Here is a watered down version of my compose file if that is of any interest:

```yml
version: "3"

services:
  identity:
    build:
      context: <Redacted>
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: https://+:443;http://+:80
      ASPNETCORE_Kestrel__Certificates__Default__Password: <Redacted>
      ASPNETCORE_Kestrel__Certificates__Default__Path: <Redacted>
      ASPNETCORE_ENVIRONMENT: Development
      IdentityConfiguration__EncryptionCertificatePath: <Redacted>
      IdentityConfiguration__EncryptionCertificatePassword: <Redacted>
      IdentityConfiguration__SigningCertificatePath: <Redacted>
      IdentityConfiguration__SigningCertificatePassword: <Redacted>      
    ports:
      - "7072:80"
      - "7073:443"
    volumes:
      - ./certificates:/https:ro

  secondservice:
    build:
      context: <Redacted>
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:80
      ASPNETCORE_ENVIRONMENT: Development
      IdentityConfiguration__Issuer: https://identity
      IdentityConfiguration__EncryptionCertificatePath: <Redacted>
      IdentityConfiguration__EncryptionCertificatePassword: <Redacted>      
    volumes:
      - ./certificates:/https:ro
```

At this point I would be happy if someone could just explain to me how I can disable the certificate verification when configuring the validation. I will use an environment variable to disable the behavior in a production environment.
